services:
  server:
    build:
      context: .
      dockerfile: Server.Dockerfile
    environment:
      GREETING: "Hey there"
  app:
    build: 
      context: .
      dockerfile: App.Dockerfile
      target: base
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c 'env && sleep infinity'